DROP TABLE DOMICILIOS IF EXISTS;
DROP TABLE PACIENTES IF EXISTS;
DROP TABLE IF EXISTS ODONTOLOGO;

CREATE TABLE DOMICILIOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(25) NOT NULL,
NUMERO INT NOT NULL,
LOCALIDAD VARCHAR(25) NOT NULL,
PROVINCIA VARCHAR(25) NOT NULL
);

CREATE TABLE PACIENTES(
ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR(25) NOT NULL,
NOMBRE VARCHAR(25) NOT NULL,
DNI VARCHAR(10) NOT NULL,
FECHA_INGRESO DATE NOT NULL,
ID_DOMICILIO INT NOT NULL);

CREATE TABLE ODONTOLOGO(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO_MATRICULA VARCHAR(25) NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    APELLIDO VARCHAR(40) NOT NULL
);
INSERT INTO ODONTOLOGO VALUES (DEFAULT, '123', 'JORGE', 'CEBALLOS');
INSERT INTO DOMICILIOS VALUES (DEFAULT, 'SIEMPRE VIVA',123,'CABA','BUENOS AIRES');
INSERT INTO PACIENTES VALUES (DEFAULT, 'PEREZ','JUAN','45566', '2024-07-15', 1);